tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
tap "osx-cross/avr"
tap "px4/px4"
brew "avrdude"
brew "dfu-programmer"
brew "dfu-util"
brew "fish"
brew "fzf"
brew "ghq"
brew "git"
brew "neovim"
brew "peco"
brew "osx-cross/avr/avr-gcc@8", link: true
brew "px4/px4/gcc-arm-none-eabi"
