[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'fatih/vim-go'

[[plugins]]
repo = 'dag/vim-fish'

[[plugins]]
repo = 'cespare/vim-toml'

[[plugins]]
repo = 'jlanzarotta/bufexplorer'

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'tpope/vim-rhubarb'

[[plugins]]
repo = 'airblade/vim-gitgutter'

[[plugins]]
repo = 'tpope/vim-endwise'

[[plugins]]
repo = 'Townk/vim-autoclose'

[[plugins]]
repo = 'junegunn/fzf.vim'
